In [13]:
import numpy as np


 a=np.array([1,2,3])
b=np.array([[2.0,5.0,6.0],[2.0,4.0,5.0,]])
print(a)
print(b)

In [23]:
a.ndim

1

In [24]:
b.shape

(2, 3)

In [26]:
a.dtype

dtype('int32')

In [27]:
a.size

3

# changing rows

In [28]:
k=np.array([[1,2,3,4,5,6],[7,8,9,10,12,13]])
print(k)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 12 13]]


In [30]:
k.shape

(2, 6)

In [35]:
k[1,-2]

12

In [37]:
k[0,:]

array([1, 2, 3, 4, 5, 6])

In [38]:
k[:,4]

array([ 5, 12])

In [43]:
k[0, 2:4:5]

array([3])

In [44]:
#arrays
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [45]:
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [46]:
np.full((2,2),88)

array([[88, 88],
       [88, 88]])

In [49]:
np.random.rand(4,2)

array([[0.31447967, 0.55262337],
       [0.01255   , 0.37986651],
       [0.2591885 , 0.63552964],
       [0.90466918, 0.5338131 ]])

In [50]:
k.T

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 12],
       [ 6, 13]])

In [52]:
np.random.randint(7,size=(3,3))

array([[1, 2, 5],
       [0, 2, 1],
       [1, 4, 3]])

In [59]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [68]:
#MATHS
m=np.array([1,2,3,4,5,6])
n=np.array([7,8,9,10,11,12])
print(m)
print(n)

[1 2 3 4 5 6]
[ 7  8  9 10 11 12]


In [69]:
m+1

array([2, 3, 4, 5, 6, 7])

In [70]:
m+2
m/2
m*2


array([ 2,  4,  6,  8, 10, 12])

In [71]:
m/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. ])

In [73]:
m*n

array([ 7, 16, 27, 40, 55, 72])

In [1]:
s='srinivas'

In [2]:
print(s.capitalize())
print(s.upper())
print(s.rjust(7))
print(s.center(100))
print(s.replace('1','sri'))
print('wo rld'.strip())
print(srinivas,len(srinivas))

Srinivas
SRINIVAS
srinivas
                                              srinivas                                              
srinivas
wo rld


NameError: name 'srinivas' is not defined

In [50]:
x={1,2,3,4,5}
y={2,4,5,8,7}
print(x)
print(y)
print(x.intersection(y))
print(x.union(y))
print(x-y)

{1, 2, 3, 4, 5}
{2, 4, 5, 7, 8}
{2, 4, 5}
{1, 2, 3, 4, 5, 7, 8}
{1, 3}


In [6]:
students={"B1":"A","B2":"B","B3":"NONE"}

In [7]:
print(students["B3"])

NONE


In [9]:
print(students.keys())
print(students.values())
print(students)
print(students.get("B3"))

dict_keys(['B1', 'B2', 'B3'])
dict_values(['A', 'B', 'NONE'])
{'B1': 'A', 'B2': 'B', 'B3': 'NONE'}
NONE


In [4]:
import numpy as np
w=[[1,2],[7,8]]
x=[[4,5],[5,6]]
i=np.array(w)
j=np.array(x)
print(i.shape,j.shape)
print(j.shape)
print(type(i))
print(type(j))
print(i)
print(j)

(2, 2) (2, 2)
(2, 2)
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[[1 2]
 [7 8]]
[[4 5]
 [5 6]]


In [8]:
print(i.T)
print(j.T)
print(i+j)
print(i*j)
E=np.matmul(i,j)
print(E)
k=np.linalg.inv(i)
print(k)

[[1 7]
 [2 8]]
[[4 5]
 [5 6]]
[[ 5  7]
 [12 14]]
[[ 4 10]
 [35 48]]
[[14 17]
 [68 83]]
[[-1.33333333  0.33333333]
 [ 1.16666667 -0.16666667]]


In [13]:
F=np.zeros((5,3))
print(F)
G=np.ones((5,3))
print(G)
h=np.eye((5))
print(h)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [16]:
l=np.random.random((5,6))
print(l)
m=np.sin(i)
print(m)

[[0.37764388 0.68612656 0.01411698 0.24493605 0.40709755 0.28374248]
 [0.35844818 0.67087656 0.87813211 0.65333296 0.64576453 0.06767622]
 [0.87722514 0.32891044 0.63702018 0.61485674 0.54502439 0.35404383]
 [0.24474817 0.23908256 0.22888848 0.02340683 0.67639996 0.49126832]
 [0.92643976 0.09592711 0.23267576 0.16261828 0.5869641  0.04792168]]
[[0.84147098 0.90929743]
 [0.6569866  0.98935825]]


In [3]:
import matplotlib.pyplot as plt
import numpy as np

In [4]:
o=np.arange(0,10,0.9)
p=np.sin(o)
q=np.cos(o)

In [5]:
fig=plt.figure(figsize(0,10,0.9))
plt.scatter(p,q,
           s=20'
            edgecolor=
           )
plt.show()

SyntaxError: EOL while scanning string literal (2751443552.py, line 3)